/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'rustdesk-napi.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./rustdesk-napi.android-arm64.node')
          } else {
            nativeBinding = require('rustdesk-napi-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'rustdesk-napi.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./rustdesk-napi.android-arm-eabi.node')
          } else {
            nativeBinding = require('rustdesk-napi-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'rustdesk-napi.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./rustdesk-napi.win32-x64-msvc.node')
          } else {
            nativeBinding = require('rustdesk-napi-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'rustdesk-napi.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./rustdesk-napi.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('rustdesk-napi-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'rustdesk-napi.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./rustdesk-napi.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('rustdesk-napi-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'rustdesk-napi.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./rustdesk-napi.darwin-universal.node')
      } else {
        nativeBinding = require('rustdesk-napi-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'rustdesk-napi.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./rustdesk-napi.darwin-x64.node')
          } else {
            nativeBinding = require('rustdesk-napi-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'rustdesk-napi.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./rustdesk-napi.darwin-arm64.node')
          } else {
            nativeBinding = require('rustdesk-napi-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'rustdesk-napi.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./rustdesk-napi.freebsd-x64.node')
      } else {
        nativeBinding = require('rustdesk-napi-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'rustdesk-napi.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rustdesk-napi.linux-x64-musl.node')
            } else {
              nativeBinding = require('rustdesk-napi-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'rustdesk-napi.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rustdesk-napi.linux-x64-gnu.node')
            } else {
              nativeBinding = require('rustdesk-napi-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'rustdesk-napi.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rustdesk-napi.linux-arm64-musl.node')
            } else {
              nativeBinding = require('rustdesk-napi-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'rustdesk-napi.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rustdesk-napi.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('rustdesk-napi-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'rustdesk-napi.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rustdesk-napi.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('rustdesk-napi-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'rustdesk-napi.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rustdesk-napi.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('rustdesk-napi-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'rustdesk-napi.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rustdesk-napi.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('rustdesk-napi-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'rustdesk-napi.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./rustdesk-napi.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('rustdesk-napi-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'rustdesk-napi.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./rustdesk-napi.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('rustdesk-napi-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { initialize, sessionCreate, sessionStart, sessionLogin, sessionClose, sessionReconnect, getFrameRgba, consumeFrame, sessionSendMouse, sessionInputKey, sessionInputString, mainGetId, mainGetOption, mainSetOption, mainGetLocalOption, mainSetLocalOption, mainGetVersion, mainGetPeer, mainPeerHasPassword, mainGetLanPeers, mainDiscover, mainGetOptions, mainSetOptions, sessionSendChat, sessionSetClipboard, sessionReadRemoteDir, sessionSendFiles, sessionCancelJob, sessionRemoveFile, sessionCreateDir, sessionToggleOption, sessionGetToggleOption, sessionRefresh, sessionLockScreen, sessionCtrlAltDel, sessionSwitchDisplay, sessionCaptureDisplays, sessionRestartRemoteDevice, sessionRecordScreen, sessionTakeScreenshot, sessionTogglePrivacyMode, sessionElevateDirect, sessionElevateWithLogon, sessionGetKeyboardMode, sessionSaveKeyboardMode, sessionGetViewStyle, sessionSaveViewStyle, sessionSaveImageQuality, sessionSetCustomFps, sessionSetOption, sessionGetOption, sessionChangePreferCodec, sessionAlternativeCodecs } = nativeBinding

module.exports.initialize = initialize
module.exports.sessionCreate = sessionCreate
module.exports.sessionStart = sessionStart
module.exports.sessionLogin = sessionLogin
module.exports.sessionClose = sessionClose
module.exports.sessionReconnect = sessionReconnect
module.exports.getFrameRgba = getFrameRgba
module.exports.consumeFrame = consumeFrame
module.exports.sessionSendMouse = sessionSendMouse
module.exports.sessionInputKey = sessionInputKey
module.exports.sessionInputString = sessionInputString
module.exports.mainGetId = mainGetId
module.exports.mainGetOption = mainGetOption
module.exports.mainSetOption = mainSetOption
module.exports.mainGetLocalOption = mainGetLocalOption
module.exports.mainSetLocalOption = mainSetLocalOption
module.exports.mainGetVersion = mainGetVersion
module.exports.mainGetPeer = mainGetPeer
module.exports.mainPeerHasPassword = mainPeerHasPassword
module.exports.mainGetLanPeers = mainGetLanPeers
module.exports.mainDiscover = mainDiscover
module.exports.mainGetOptions = mainGetOptions
module.exports.mainSetOptions = mainSetOptions
module.exports.sessionSendChat = sessionSendChat
module.exports.sessionSetClipboard = sessionSetClipboard
module.exports.sessionReadRemoteDir = sessionReadRemoteDir
module.exports.sessionSendFiles = sessionSendFiles
module.exports.sessionCancelJob = sessionCancelJob
module.exports.sessionRemoveFile = sessionRemoveFile
module.exports.sessionCreateDir = sessionCreateDir
module.exports.sessionToggleOption = sessionToggleOption
module.exports.sessionGetToggleOption = sessionGetToggleOption
module.exports.sessionRefresh = sessionRefresh
module.exports.sessionLockScreen = sessionLockScreen
module.exports.sessionCtrlAltDel = sessionCtrlAltDel
module.exports.sessionSwitchDisplay = sessionSwitchDisplay
module.exports.sessionCaptureDisplays = sessionCaptureDisplays
module.exports.sessionRestartRemoteDevice = sessionRestartRemoteDevice
module.exports.sessionRecordScreen = sessionRecordScreen
module.exports.sessionTakeScreenshot = sessionTakeScreenshot
module.exports.sessionTogglePrivacyMode = sessionTogglePrivacyMode
module.exports.sessionElevateDirect = sessionElevateDirect
module.exports.sessionElevateWithLogon = sessionElevateWithLogon
module.exports.sessionGetKeyboardMode = sessionGetKeyboardMode
module.exports.sessionSaveKeyboardMode = sessionSaveKeyboardMode
module.exports.sessionGetViewStyle = sessionGetViewStyle
module.exports.sessionSaveViewStyle = sessionSaveViewStyle
module.exports.sessionSaveImageQuality = sessionSaveImageQuality
module.exports.sessionSetCustomFps = sessionSetCustomFps
module.exports.sessionSetOption = sessionSetOption
module.exports.sessionGetOption = sessionGetOption
module.exports.sessionChangePreferCodec = sessionChangePreferCodec
module.exports.sessionAlternativeCodecs = sessionAlternativeCodecs
