/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Initialize the RustDesk core. Must be called before any other function. */
export declare function initialize(appDir: string): void
/** Create a new remote desktop session. */
export declare function sessionCreate(sessionId: string, peerId: string, password?: string | undefined | null, isFileTransfer?: boolean | undefined | null, isPortForward?: boolean | undefined | null, isRdp?: boolean | undefined | null, isTerminal?: boolean | undefined | null, forceRelay?: boolean | undefined | null): void
/**
 * Start a session. Begins the connection IO loop.
 * `event_callback` receives JSON event strings from Rust.
 * `frame_callback` receives JSON frame notifications when a new frame is ready.
 */
export declare function sessionStart(sessionId: string, eventCallback: (event: string) => void, frameCallback: (notification: string) => void): void
/** Send login credentials for a session */
export declare function sessionLogin(sessionId: string, osUsername: string, osPassword: string, password: string, remember: boolean): void
/** Close a session */
export declare function sessionClose(sessionId: string): void
/** Reconnect a session */
export declare function sessionReconnect(sessionId: string, forceRelay?: boolean | undefined | null): void
/**
 * Get the current video frame as a raw BGRA buffer and consume it atomically.
 * Returns null if no frame is available.
 * The BGRA→RGBA swizzle is done in the WebGL fragment shader (zero-cost GPU op).
 * This combines get + consume into one call to avoid an extra IPC round-trip.
 */
export declare function getFrameRgba(sessionId: string, display: number): Buffer | null
/**
 * Mark the current frame as consumed, allowing Rust to write the next frame.
 * NOTE: With the new take_frame(), calling get_frame_rgba already consumes.
 * This is kept for backward compatibility but is now a no-op.
 */
export declare function consumeFrame(sessionId: string, display: number): void
/**
 * Send a mouse event to the remote peer.
 * `msg` is a JSON string: {"type":"move","x":"100","y":"200","buttons":"left",...}
 */
export declare function sessionSendMouse(sessionId: string, msg: string): void
/** Send a key input event to the remote peer. */
export declare function sessionInputKey(sessionId: string, name: string, down: boolean, press: boolean, alt: boolean, ctrl: boolean, shift: boolean, command: boolean): void
/** Send a text string to the remote peer (for paste operations). */
export declare function sessionInputString(sessionId: string, value: string): void
/** Get this device's RustDesk ID */
export declare function mainGetId(): string
/** Get an option value */
export declare function mainGetOption(key: string): string
/** Set an option value */
export declare function mainSetOption(key: string, value: string): void
/** Get a local option value */
export declare function mainGetLocalOption(key: string): string
/** Set a local option value */
export declare function mainSetLocalOption(key: string, value: string): void
/** Get RustDesk version */
export declare function mainGetVersion(): string
/** Get peer config as JSON */
export declare function mainGetPeer(id: string): string
/** Check if a peer has a saved password */
export declare function mainPeerHasPassword(id: string): boolean
/** Get LAN peers as JSON */
export declare function mainGetLanPeers(): string
/** Trigger LAN peer discovery */
export declare function mainDiscover(): void
/** Get all options as JSON */
export declare function mainGetOptions(): string
/** Set multiple options from JSON string */
export declare function mainSetOptions(json: string): void
/** Send a chat message to the remote peer */
export declare function sessionSendChat(sessionId: string, text: string): void
/** Update the clipboard on the remote peer */
export declare function sessionSetClipboard(sessionId: string, text: string): void
/** Read a remote directory */
export declare function sessionReadRemoteDir(sessionId: string, path: string, includeHidden: boolean): void
/** Send files between local and remote */
export declare function sessionSendFiles(sessionId: string, actId: number, path: string, to: string, fileNum: number, includeHidden: boolean, isRemote: boolean): void
/** Cancel a file transfer job */
export declare function sessionCancelJob(sessionId: string, actId: number): void
/** Remove a file on remote */
export declare function sessionRemoveFile(sessionId: string, actId: number, path: string, fileNum: number, isRemote: boolean): void
/** Create a directory on remote */
export declare function sessionCreateDir(sessionId: string, actId: number, path: string, isRemote: boolean): void
/** Toggle a session option */
export declare function sessionToggleOption(sessionId: string, value: string): void
/** Get a session toggle option value */
export declare function sessionGetToggleOption(sessionId: string, arg: string): boolean
/** Refresh the remote screen */
export declare function sessionRefresh(sessionId: string, display: number): void
/** Lock remote screen */
export declare function sessionLockScreen(sessionId: string): void
/** Send Ctrl+Alt+Del to remote */
export declare function sessionCtrlAltDel(sessionId: string): void
/** Switch to a specific display on the remote peer */
export declare function sessionSwitchDisplay(sessionId: string, display: number): void
/** Capture multiple displays (for "all displays" mode) */
export declare function sessionCaptureDisplays(sessionId: string, add: Array<number>, sub: Array<number>, set: Array<number>): void
/** Restart the remote device */
export declare function sessionRestartRemoteDevice(sessionId: string): void
/** Start or stop screen recording */
export declare function sessionRecordScreen(sessionId: string, start: boolean): void
/** Take a screenshot of the remote display */
export declare function sessionTakeScreenshot(sessionId: string, display: number): void
/** Toggle privacy mode on the remote device */
export declare function sessionTogglePrivacyMode(sessionId: string, implKey: string, on: boolean): void
/** Request direct elevation (run as administrator) on the remote device */
export declare function sessionElevateDirect(sessionId: string): void
/** Elevate with logon credentials on the remote device */
export declare function sessionElevateWithLogon(sessionId: string, username: string, password: string): void
/** Get the current keyboard mode for a session */
export declare function sessionGetKeyboardMode(sessionId: string): string
/** Save keyboard mode for a session */
export declare function sessionSaveKeyboardMode(sessionId: string, value: string): void
/** Get the view style for a session */
export declare function sessionGetViewStyle(sessionId: string): string
/** Save the view style for a session */
export declare function sessionSaveViewStyle(sessionId: string, value: string): void
/** Set image quality preset: "best", "balanced", "low", "custom" */
export declare function sessionSaveImageQuality(sessionId: string, value: string): void
/** Set custom FPS */
export declare function sessionSetCustomFps(sessionId: string, fps: number): void
/** Set a peer session option (e.g. "codec-preference" = "vp9") */
export declare function sessionSetOption(sessionId: string, key: string, value: string): void
/** Get a peer session option value */
export declare function sessionGetOption(sessionId: string, key: string): string
/**
 * Notify the server that codec preference has changed.
 * Must be called after session_set_option("codec-preference", ...) to take effect.
 */
export declare function sessionChangePreferCodec(sessionId: string): void
/** Get supported alternative codecs as JSON: {"vp8":bool,"av1":bool,"h264":bool,"h265":bool} */
export declare function sessionAlternativeCodecs(sessionId: string): string
